# Site settings
title: AppADay
description: "An app a day keeps the FOMO away."
url: "http://appaday.co"
author: "Johnny Appleseed"
keywords: "app,curated"

exclude: ["readme.md","CNAME"]
include: []
timezone: America/New_York
